### ISSUE TITLE
Button not support `isUp`

### ISSUE THREAD

**Issue by NatpakalJAM** [ShawnHymel/phaser-plugin-virtual-gamepad#3]
## Button not support `isUp`

Button support only `isDown`.

### code
```
function update() {
    if (fireButton.isDown) {
        console.log('button down');
    }
    if (fireButton.isUp) {
        console.log('button up');
    }
}
```
### output: 

![image](https://user-images.githubusercontent.com/26151258/58607582-69b53a00-82ca-11e9-8840-f07a7fe7d920.png)

**Comment by ShawnHymel** [comment]
Only isDown is implemented. Use `!fireButton.isDown` to see if the button is up.
